pipeline {
    agent any

    environment {
        IMAGE_NAME = "YOUR_NEXUS_IP:8082/php-ecommerce"
        SONARQUBE = "SonarQube"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/YOUR-REPO/php-ecommerce-devops.git'
            }
        }

        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv("${SONARQUBE}") {
                    sh 'sonar-scanner'
                }
            }
        }

        stage('Build Image') {
            steps {
                sh "docker build -t $IMAGE_NAME:$BUILD_NUMBER ."
            }
        }

        stage('Push to Nexus') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                    docker login YOUR_NEXUS_IP:8082 -u $USER -p $PASS
                    docker push $IMAGE_NAME:$BUILD_NUMBER
                    """
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh """
                sed -i 's|IMAGE_TAG|$BUILD_NUMBER|g' k8s/deployment.yaml
                kubectl apply -f k8s/
                """
            }
        }
    }
}
